 BEGIN
 FOR x IN 1..10
 LOOP
 DBMS_OUTPUT.PUT_LINE(x);
 END LOOP;
 END;
 /



 BEGIN
 FOR X IN REVERSE 1..10 LOOP
 DBMS_OUTPUT.PUT_LINE(X);
 END LOOP;
 END;
 /



 DECLARE
 D1 DATE;
 D2 DATE;
 BEGIN
 D1 := '01-JAN-25';
 D2 := '31-DEC-25';
 WHILE(D1 <= D2)
 LOOP
 DBMS_OUTPUT.PUT_LINE(D1);
 D1 := D1 + 1;
 END LOOP;
 END;
 /


 CREATE TABLE STUDENT222 (
     SID NUMBER(10) ,
     SNAME VARCHAR2(10),
     SUB1 NUMBER(10),
     SUB2 NUMBER(10),
     SUB3 NUMBER(10)
 );



 CREATE TABLE RESULTS (
     SID NUMBER(10) ,
     TOTAL NUMBER(10),
     AVG NUMBER(4,2),
     RESULT VARCHAR2(10)
 );

 INSERT INTO STUDENT222 VALUES (1001, 'SURYA', 80, 60, 74);
 INSERT INTO STUDENT222 VALUES (1002, 'ANUSHKA', 56, 30, 40);


 DECLARE
 CURSOR C1 IS SELECT SID, SUB1, SUB2, SUB3 FROM STUDENT222;
 R RESULTS%ROWTYPE;
 BEGIN
 FOR I IN C1
 LOOP
 R.TOTAL := I.SUB1 + I.SUB2 + I.SUB3;
 R.AVG := R.TOTAL/3;
 IF I.SUB1 >= 35 AND I.SUB2 >= 35 AND I.SUB3 >= 35 THEN
 R.RESULT := 'PASS';
 ELSE
 R.RESULT := 'FAIL';
 END IF;
 INSERT INTO RESULTS VALUES(I.SID, R.TOTAL, R.AVG, R.RESULT);
 END LOOP;
 COMMIT;
 END;
 /