SELECT * FROM EMP;

SELECT * FROM EMP WHERE ROWNUM = 1;

SELECT * FROM EMP WHERE ROWNUM BETWEEN 1 AND 5;

SELECT * FROM EMP
MINUS
SELECT * FROM
    (SELECT * FROM EMP
        WHERE
            ROWNUM <= (SELECT COUNT(*)-2 FROM EMP));

SELECT * FROM (
    SELECT * FROM EMP
        ORDER BY EMPNO DESC)
    WHERE ROWNUM <= 2;

select * from (
    select rownum r,ename,sal from emp)
where r=2;

SELECT * FROM (
    SELECT EMPNO, ENAME,SAL, JOB, ROWNUM R
        FROM EMP)
    WHERE R BETWEEN 4 AND 8;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, ROWNUM R
        FROM EMP)
    WHERE R IN(2, 3, 5, 6, 10);

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, ROWNUM R
    FROM EMP)
    WHERE R= MOD(R, 2);

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, ROWNUM AS R
    FROM EMP)
    WHERE MOD(R, 2) = 0;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, ROWNUM AS R
    FROM EMP)
    WHERE R IN(1, 14);

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, ROWNUM AS R
    FROM EMP)
    WHERE R = 1 OR R = (SELECT COUNT(*) FROM EMP);

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, ROWNUM AS R
    FROM EMP)
    WHERE R >=3;

select * from emp
    where sal IN (
        select max(sal)
        from emp
        group by deptno);

select * from emp
    where
    deptno>all(10,20);

  SELECT * FROM EMP
    WHERE ENAME IN ('SMITH', 'BLAKE');

  SELECT * FROM EMP
    WHERE JOB > ANY('SMITH', 'BLAKE');

  SELECT * FROM EMP
    WHERE SAL > ALL(
        SELECT SAL FROM EMP
        WHERE JOB = 'MANAGER');

  SELECT * FROM EMP666
    WHERE GENDER = 'M' AND SAL > ALL(
        SELECT SAL FROM EMP666
        WHERE GENDER = 'F');