SELECT * FROM EMP;

SELECT * FROM EMP WHERE ROWNUM = 1;

SELECT * FROM EMP WHERE ROWNUM BETWEEN 1 AND 5;

SELECT * FROM EMP
MINUS
SELECT * FROM
    (SELECT * FROM EMP
        WHERE
            ROWNUM <= (SELECT COUNT(*)-2 FROM EMP));

SELECT * FROM (
    SELECT * FROM EMP
        ORDER BY EMPNO DESC)
    WHERE ROWNUM <= 2;