SELECT * FROM (
    SELECT ENAME, SAL, SAL*12 AS ANNSAL
    FROM EMP
) WHERE ANNSAL > 30000;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL,  FROM EMP
    ORDER BY SAL DESC
) WHERE ROWNUM <= 5;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO, DENSE_RANK()
        OVER (ORDER BY SAL DESC) AS SALARY_RANK
    FROM EMP
)
WHERE SALARY_RANK = 2;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO,
        DENSE_RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS DEPT_SALARY_RANK
    FROM EMP
)
WHERE DEPT_SALARY_RANK = 3;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO,
        DENSE_RANK() OVER (ORDER BY SAL) AS SAL_RANK
    FROM EMP
    )
WHERE SAL_RANK = 5;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO,
           DENSE_RANK() OVER (ORDER BY SAL DESC) AS SAL_RANK
    FROM EMP
)
WHERE SAL_RANK = &N;

SELECT * FROM (
    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO,
    DENSE_RANK() OVER (ORDER BY SAL) AS S_DENSE_RANK,
    RANK() OVER (ORDER BY SAL) AS S_RANK
    FROM EMP
);
