CREATE TABLE DEPARTMENTS
(
DEPTNO NUMBER(10) PRIMARY KEY,
DNAME VARCHAR2(10)
);


CREATE TABLE EMPLOYEES
(
EMPNO NUMBER(10),
ENAME VARCHAR2(10),
DEPTNO NUMBER(10) REFERENCES DEPARTMENTS(DEPTNO)
);


INSERT INTO DEPARTMENTS VALUES(10,'HR');
INSERT INTO DEPARTMENTS VALUES(20,'IT');
INSERT INTO DEPARTMENTS VALUES(40,'FINANCE');

INSERT INTO  EMPLOYEES  VALUES(1,'KIRAN',10);
INSERT INTO  EMPLOYEES  VALUES(2,'GOWTHAM',20);
INSERT INTO  EMPLOYEES  VALUES(3,'SURYA',NULL);
INSERT INTO  EMPLOYEES  VALUES(4,'ANUSHKA',20);




CREATE TABLE EMPLOYEE_DETAILS (
        EMPID NUMBER(4) PRIMARY KEY,
        NAME VARCHAR2(10) ,
        DOB DATE,
        STATE VARCHAR2(10)
   );

 CREATE TABLE EMPLOYEE_SALARY (
        ID NUMBER(4) PRIMARY KEY,
        SALARY NUMBER(10, 2)
   );


INSERT INTO EMPLOYEE_DETAILS VALUES(1, 'JOHN', '23-APR-95', 'NY');
INSERT INTO EMPLOYEE_DETAILS VALUES(2, 'SMITH', '15-AUG-90', 'CA');
INSERT INTO EMPLOYEE_DETAILS VALUES(3, 'ROHAN', '27-APR-96', 'TX');
INSERT INTO EMPLOYEE_DETAILS VALUES(4, 'JOHNSON', '12-FEB-75', 'CA');
INSERT INTO EMPLOYEE_DETAILS VALUES(5, 'BROWN', '05-NOV-00', 'AL');
INSERT INTO EMPLOYEE_DETAILS VALUES(6, 'JILL', '15-JUN-99', 'CA');
INSERT INTO EMPLOYEE_DETAILS VALUES(7, 'JAMES', '12-SEP-83', 'WA');
INSERT INTO EMPLOYEE_DETAILS VALUES(8, 'JACK', '25-OCT-82', 'CA');



INSERT INTO EMPLOYEE_SALARY VALUES(1, 15000);
INSERT INTO EMPLOYEE_SALARY VALUES(2, 20000);
INSERT INTO EMPLOYEE_SALARY VALUES(3, 25000);
INSERT INTO EMPLOYEE_SALARY VALUES(4, 18000);
INSERT INTO EMPLOYEE_SALARY VALUES(5, 35000);
INSERT INTO EMPLOYEE_SALARY VALUES(6, 40000);
INSERT INTO EMPLOYEE_SALARY VALUES(7, 45000);

CREATE TABLE COURIER (
    COURIER_ID NUMBER(5) PRIMARY KEY,
    FROM_ADDRESS VARCHAR2(15),
    TO_ADDRESS VARCHAR2(10),
    EXPECTED_DELIVERY_DATE DATE
);



INSERT INTO COURIER VALUES (101, 'Chennai', 'Mumbai', '15-JAN-2025');
INSERT INTO COURIER VALUES (102, 'Delhi', 'Bangalore','20-JAN-2025');
INSERT INTO COURIER VALUES (103, 'Hyderabad', 'Pune', '25-FEB-2025');
INSERT INTO COURIER VALUES (104, 'Kolkata', 'Ahmedabad','05-JAN-2025');
INSERT INTO COURIER VALUES (105, 'Mumbai', 'Delhi', '10-MAR-2025');


CREATE TABLE COURIER_STATUS (
    COURIER_ID NUMBER(5),
    STATUS VARCHAR2(10),
    ACTUAL_DELIVERED_DATE DATE,
    FOREIGN KEY (COURIER_ID) REFERENCES COURIER(COURIER_ID)
);

INSERT INTO COURIER_STATUS VALUES (101, 'Delivered','16-JAN-2025');
INSERT INTO COURIER_STATUS VALUES (102, 'In Transit', NULL);
INSERT INTO COURIER_STATUS VALUES (103, 'Delivered', '26-FEB-2025');
INSERT INTO COURIER_STATUS VALUES (104, 'Delivered', '06-JAN-2025');
INSERT INTO COURIER_STATUS VALUES (105, 'Delivered',  '11-MAR-2025');

commit;

SELECT ENAME, DNAME
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON E.DEPTNO = D.DEPTNO;

SQL> SELECT ENAME, DNAME FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPTNO = D.DEPTNO;

SELECT ENAME, DNAME FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM EMPLOYEE_DETAILS ED INNER JOIN EMPLOYEE_SALARY ES ON ED.EMPID = ES.ID;





DROP TABLE  EMPLOYEES;
DROP TABLE DEPARTMENTS;

DROP TABLE EMPLOYEE_DETAILS;
DROP TABLE EMPLOYEE_SALARY;

DROP TABLE COURIER_STATUS;
DROP TABLE COURIER;