CREATE TABLE students(
      sid number(10),
      sname varchar(20),
      marks number(5),
      grade varchar(2),
      dob date
   );
INSERT INTO STUDENTS VALUES(1, 'SURYA', 82, 'B', '31-DEC-1997');
INSERT INTO STUDENTS VALUES(2, 'KIRAN', 20, 'F', '18-SEP-1996');
INSERT INTO STUDENTS VALUES(3, 'ANUSHKA', 98, 'A', '22-APR-1998');
INSERT INTO STUDENTS VALUES(4, 'GOWTHAM', 64, 'C', '06-JAN-1995');
INSERT INTO STUDENTS VALUES(5, 'NITHISH', 45, 'D', '12-MAR-1996');

ALTER TABLE STUDENTS ADD (EMAIL VARCHAR(20));

ALTER TABLE STUDENTS MODIFY (SNAME VARCHAR2(30));

ALTER TABLE STUDENTS DROP (GRADE);

ALTER TABLE STUDENTS RENAME COLUMN SNAME TO NAME;

DROP TABLE STUDENTS;

SHOW RECYCLEBIN;

ALTER TABLE STUDENTS RENAME TO STUDENTSDATA;





