SELECT * FROM EMP;
SELECT * FROM EMP WHERE JOB = 'MANAGER';
SELECT * FROM EMP WHERE DEPTNO IN (10, 30);
SELECT * FROM EMP WHERE COMM IS NULL;
DESC EMP;
SELECT * FROM EMP WHERE MGR IS NULL;

SELECT COUNT(*) FROM EMP WHERE JOB = 'CLERK';
SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP WHERE HIREDATE LIKE '%81';
SELECT * FROM EMP WHERE JOB IN('MANAGER','CLERK') AND SAL BETWEEN 1500 AND 3000 AND HIREDATE LIKE '%81' AND DEPTNO NOT IN(10,20);

DESC USERS;
SELECT NAME AS USERNAME, EMAIL AS EMAILID FROM USERS WHERE PHONE_NUMBER LIKE'%29';
SELECT * FROM EMP WHERE JOB = 'MANAGER' AND SAL = SAL * 1.2 AND ENAME LIKE'A%S';
UPDATE EMP SET JOB = 'MANAGER' WHERE SAL = SAL * 1.2 AND ENAME LIKE'A%S';