BEGIN
    DBMS_OUTPUT.PUT_LINE('WELCOME TO PL/SQL CLASSES FOR MY DEAR WONDERFULL BATACH53');
END;
/


DECLARE
    X NUMBER(10);
    Y NUMBER(10);
    C NUMBER(10);
BEGIN
    X := &X;
    Y := &Y;
    C := X + Y;

    DBMS_OUTPUT.PUT_LINE(C);
END;
/


DECLARE
    V_EMPNO NUMBER(10);
    V_ENAME VARCHAR(10);
    V_SAL NUMBER;
BEGIN
    V_EMPNO := &EMPNO;
    SELECT EMPNO, ENAME, SAL
    INTO V_EMPNO, V_ENAME, V_SAL
    FROM EMP
    WHERE EMPNO = V_EMPNO;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME IS '||V_ENAME||' AND '||V_SAL);
END;
/


DECLARE
    EXP NUMBER;
    V_HIREDATE DATE;
    V_EMPNO NUMBER := &EMPNO;
BEGIN
    SELECT HIREDATE
    INTO V_HIREDATE
    FROM EMP
    WHERE EMPNO = V_EMPNO;

    EXP := TRUNC((SYSDATE - V_HIREDATE)/365);

    DBMS_OUTPUT.PUT_LINE('EXPERIENCE '||EXP);
END;
/


DECLARE
    V_EMPNO EMP.EMPNO%TYPE;
    V_ENAME EMP.ENAME%TYPE;
    V_SAL EMP.SAL%TYPE;
    V_HIREDATE EMP.HIREDATE%TYPE;
BEGIN
    V_EMPNO := &EMPNO;
    SELECT ENAME, SAL, HIREDATE
    INTO V_ENAME, V_SAL, V_HIREDATE
    FROM EMP
    WHERE EMPNO = V_EMPNO;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NUMBER '||V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||V_ENAME);
    DBMS_OUTPUT.PUT_LINE('SALLARY '||V_SAL);
    DBMS_OUTPUT.PUT_LINE('HIREDATE '||TO_CHAR(V_HIREDATE,'DD-MON-YYYY'));
END;
/


DECLARE
    V_EMPNO EMP.EMPNO%TYPE;
    V_ENAME EMP.ENAME%TYPE;
    V_SAL EMP.SAL%TYPE;
    V_HIREDATE EMP.HIREDATE%TYPE;
BEGIN
    V_EMPNO := &EMPNO;
    SELECT ENAME, SAL, HIREDATE
    INTO V_ENAME, V_SAL, V_HIREDATE
    FROM EMP
    WHERE EMPNO = V_EMPNO;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NUMBER '||V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME '||V_ENAME);
    DBMS_OUTPUT.PUT_LINE('SALLARY '||V_SAL);
    DBMS_OUTPUT.PUT_LINE('HIREDATE '||TO_CHAR(V_HIREDATE,'DD-MON-YYYY'));
END;
/
