CREATE TABLE FACULTY (
    FID NUMBER(10) PRIMARY KEY,
    FNAME VARCHAR(20),
    SUBJECT VARCHAR(10),
    AGE NUMBER(2)
);

CREATE TABLE STUDENTENROLLMENT (
    SNAME VARCHAR2(10),
    FID NUMBER(10) REFERENCES Faculty(FID)
);

INSERT INTO FACULTY VALUES (1001, 'MURALI', 'ORACLE', 38);
INSERT INTO FACULTY VALUES(1002, 'HARI KRISHNA', 'CORE JAVA', 36);
INSERT INTO FACULTY VALUES(1003, 'SHIV CHAITANYA', 'ORACLE', 32);

INSERT INTO STUDENTENROLLMENT VALUES('GOWTHAM',1001);
INSERT INTO STUDENTENROLLMENT VALUES('SUBBARAO',1001);
INSERT INTO STUDENTENROLLMENT VALUES('GOWTHAM',1002);
INSERT INTO STUDENTENROLLMENT VALUES('SURYA', 1001);
INSERT INTO STUDENTENROLLMENT VALUES('ANUSHKA',NULL);
INSERT INTO STUDENTENROLLMENT VALUES('KIRAN',NULL);
INSERT INTO STUDENTENROLLMENT VALUES('SUBBARAO',1002);
INSERT INTO STUDENTENROLLMENT VALUES('KAVYA', 1003);

COMMIT;


SELECT * FROM STUDENTENROLLMENT;

SELECT * FROM FACULTY;

SELECT *
FROM STUDENTENROLLMENT S INNER JOIN FACULTY F
ON S.FID = F.FID;

select sname, fname, subject, age
from studentenrollment s Inner Join faculty f on s.fid = f.fid where subject = 'ORACLE';
