  SELECT * FROM EMP;
  SELECT * FROM DEPT;

  SELECT ENAME, DNAME
  FROM EMP INNER JOIN DEPT
  ON EMP.DEPTNO = DEPT.DEPTNO;

  SELECT DEPT.DNAME, SUM(EMP.SAL)
  FROM EMP JOIN DEPT
  ON EMP.DEPTNO = DEPT.DEPTNO
  GROUP BY DNAME;

  SELECT DEPT.DNAME, SUM(SAL)
  FROM EMP INNER JOIN DEPT
  ON EMP.DEPTNO = DEPT.DEPTNO
  GROUP BY DNAME HAVING SUM(SAL) > 9000;