CREATE VIEW V1 AS SELECT EMPNO, ENAME, DEPTNO FROM EMP;
INSERT INTO V1 VALUES(121, 'HARI', 20);
INSERT INTO V1 VALUES(122, 'HARRIS', 20);
INSERT INTO V1 VALUES(123, 'SHIZUKU', 10);
INSERT INTO V1 VALUES(124, 'DANNY', 30);

CREATE VIEW V2 AS SELECT * FROM EMP WHERE DEPTNO = 10;

CREATE VIEW DSAL AS SELECT DEPTNO ,MAX(SAL) AS MAXSAL FROM EMP GROUP BY DEPTNO;
SELECT * FROM DSAL;

create table test1(name varchar2(10));
create table test2(sub varchar2(10));

CREATE VIEW V3 AS SELECT NAME, SUB FROM TEST1, TEST2;

CREATE VIEW V4 AS SELECT * FROM EMP WHERE DEPTNO = '20' WITH CHECK OPTION;

