SELECT * FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP);

SELECT *FROM EMP WHERE HIREDATE = (SELECT MIN(HIREDATE)FROM EMP);

SELECT * FROM EMP WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 20);

SELECT * FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 10);

SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH';

SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');

SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');

SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP));

SELECT * FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP));

SELECT * FROM EMP WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'BLAKE');

SELECT * FROM DEPT WHERE DNAME = (SELECT DNAME FROM DEPT WHERE DNAME = 'SALES');

SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN') AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'JONES');

 SELECT * FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME='BLAKE');

